export default blockedShortcuts = [

    'CmdOrCtrl+A',
    'CmdOrCtrl+B',
    'CmdOrCtrl+C',
    'CmdOrCtrl+D',
    'CmdOrCtrl+E',
    'CmdOrCtrl+F',
    'CmdOrCtrl+G',
    'CmdOrCtrl+H',
    'CmdOrCtrl+I',
    'CmdOrCtrl+J',
    'CmdOrCtrl+K',
    'CmdOrCtrl+L',
    'CmdOrCtrl+M',
    'CmdOrCtrl+N',
    'CmdOrCtrl+O',
    'CmdOrCtrl+P',
    'CmdOrCtrl+Q',
    'CmdOrCtrl+R',
    'CmdOrCtrl+S',
    'CmdOrCtrl+T',
    'CmdOrCtrl+U',
    'CmdOrCtrl+V',
    'CmdOrCtrl+W',
    'CmdOrCtrl+X',
    'CmdOrCtrl+Y',
    'CmdOrCtrl+Z',

    'CmdOrCtrl+0',
    'CmdOrCtrl+1',
    'CmdOrCtrl+2',
    'CmdOrCtrl+3',
    'CmdOrCtrl+4',
    'CmdOrCtrl+5',
    'CmdOrCtrl+6',
    'CmdOrCtrl+7',
    'CmdOrCtrl+8',
    'CmdOrCtrl+9',

    'CmdOrCtrl+~',
    'CmdOrCtrl+!',
    'CmdOrCtrl+@',
    'CmdOrCtrl+#',
    'CmdOrCtrl+$',

    'CmdOrCtrl+Plus',
    'CmdOrCtrl+Space',
    'CmdOrCtrl+Tab',
    'CmdOrCtrl+Capslock',
    'CmdOrCtrl+Numlock',
    'CmdOrCtrl+Scrollock',
    'CmdOrCtrl+Backspace',
    'CmdOrCtrl+Delete',
    'CmdOrCtrl+Insert',
    'CmdOrCtrl+Return',

    'CmdOrCtrl+Up',
    'CmdOrCtrl+Down',
    'CmdOrCtrl+Left',
    'CmdOrCtrl+Right',

    'CmdOrCtrl+Esc',
    'CmdOrCtrl+PageUp',
    'CmdOrCtrl+PageDown',

    'CmdOrCtrl+F1',
    'CmdOrCtrl+F2',
    'CmdOrCtrl+F3',
    'CmdOrCtrl+F4',
    'CmdOrCtrl+F5',
    'CmdOrCtrl+F6',
    'CmdOrCtrl+F7',
    'CmdOrCtrl+F8',
    'CmdOrCtrl+F9',
    'CmdOrCtrl+F10',
    'CmdOrCtrl+F11',
    'CmdOrCtrl+F12',

    'Alt+A',
    'Alt+B',
    'Alt+C',
    'Alt+D',
    'Alt+E',
    'Alt+F',
    'Alt+G',
    'Alt+H',
    'Alt+I',
    'Alt+J',
    'Alt+K',
    'Alt+L',
    'Alt+M',
    'Alt+N',
    'Alt+O',
    'Alt+P',
    'Alt+Q',
    'Alt+R',
    'Alt+S',
    'Alt+T',
    'Alt+U',
    'Alt+V',
    'Alt+W',
    'Alt+X',
    'Alt+Y',
    'Alt+Z',

    'Alt+0',
    'Alt+1',
    'Alt+2',
    'Alt+3',
    'Alt+4',
    'Alt+5',
    'Alt+6',
    'Alt+7',
    'Alt+8',
    'Alt+9',

    'Alt+~',
    'Alt+!',
    'Alt+@',
    'Alt+#',
    'Alt+$',

    'Alt+Plus',
    'Alt+Space',
    'Alt+Tab',
    'Alt+Capslock',
    'Alt+Numlock',
    'Alt+Scrollock',
    'Alt+Backspace',
    'Alt+Delete',
    'Alt+Insert',
    'Alt+Return',

    'Alt+Up',
    'Alt+Down',
    'Alt+Left',
    'Alt+Right',

    'Alt+Esc',
    'Alt+PageUp',
    'Alt+PageDown',

    'Alt+F1',
    'Alt+F2',
    'Alt+F3',
    'Alt+F4',
    'Alt+F5',
    'Alt+F6',
    'Alt+F7',
    'Alt+F8',
    'Alt+F9',
    'Alt+F10',
    'Alt+F11',
    'Alt+F12',

    'Option+A',
    'Option+B',
    'Option+C',
    'Option+D',
    'Option+E',
    'Option+F',
    'Option+G',
    'Option+H',
    'Option+I',
    'Option+J',
    'Option+K',
    'Option+L',
    'Option+M',
    'Option+N',
    'Option+O',
    'Option+P',
    'Option+Q',
    'Option+R',
    'Option+S',
    'Option+T',
    'Option+U',
    'Option+V',
    'Option+W',
    'Option+X',
    'Option+Y',
    'Option+Z',

    'Option+0',
    'Option+1',
    'Option+2',
    'Option+3',
    'Option+4',
    'Option+5',
    'Option+6',
    'Option+7',
    'Option+8',
    'Option+9',

    'Option+~',
    'Option+!',
    'Option+@',
    'Option+#',
    'Option+$',

    'Option+Plus',
    'Option+Space',
    'Option+Tab',
    'Option+Capslock',
    'Option+Numlock',
    'Option+Scrollock',
    'Option+Backspace',
    'Option+Delete',
    'Option+Insert',
    'Option+Return',

    'Option+Up',
    'Option+Down',
    'Option+Left',
    'Option+Right',

    'Option+Esc',
    'Option+PageUp',
    'Option+PageDown',

    'Option+F1',
    'Option+F2',
    'Option+F3',
    'Option+F4',
    'Option+F5',
    'Option+F6',
    'Option+F7',
    'Option+F8',
    'Option+F9',
    'Option+F10',
    'Option+F11',
    'Option+F12',

    'AltGr+A',
    'AltGr+B',
    'AltGr+C',
    'AltGr+D',
    'AltGr+E',
    'AltGr+F',
    'AltGr+G',
    'AltGr+H',
    'AltGr+I',
    'AltGr+J',
    'AltGr+K',
    'AltGr+L',
    'AltGr+M',
    'AltGr+N',
    'AltGr+O',
    'AltGr+P',
    'AltGr+Q',
    'AltGr+R',
    'AltGr+S',
    'AltGr+T',
    'AltGr+U',
    'AltGr+V',
    'AltGr+W',
    'AltGr+X',
    'AltGr+Y',
    'AltGr+Z',

    'AltGr+0',
    'AltGr+1',
    'AltGr+2',
    'AltGr+3',
    'AltGr+4',
    'AltGr+5',
    'AltGr+6',
    'AltGr+7',
    'AltGr+8',
    'AltGr+9',

    'AltGr+~',
    'AltGr+!',
    'AltGr+@',
    'AltGr+#',
    'AltGr+$',

    'AltGr+Plus',
    'AltGr+Space',
    'AltGr+Tab',
    'AltGr+Capslock',
    'AltGr+Numlock',
    'AltGr+Scrollock',
    'AltGr+Backspace',
    'AltGr+Delete',
    'AltGr+Insert',
    'AltGr+Return',

    'AltGr+Up',
    'AltGr+Down',
    'AltGr+Left',
    'AltGr+Right',

    'AltGr+Esc',
    'AltGr+PageUp',
    'AltGr+PageDown',

    'AltGr+F1',
    'AltGr+F2',
    'AltGr+F3',
    'AltGr+F4',
    'AltGr+F5',
    'AltGr+F6',
    'AltGr+F7',
    'AltGr+F8',
    'AltGr+F9',
    'AltGr+F10',
    'AltGr+F11',
    'AltGr+F12',

    'Shift+Plus',
    'Shift+Space',
    'Shift+Tab',
    'Shift+Capslock',
    'Shift+Numlock',
    'Shift+Scrollock',
    'Shift+Backspace',
    'Shift+Delete',
    'Shift+Insert',
    // 'Shift+Return',

    'Shift+Up',
    'Shift+Down',
    'Shift+Left',
    'Shift+Right',

    'Shift+Esc',
    'Shift+PageUp',
    'Shift+PageDown',

    'Shift+F1',
    'Shift+F2',
    'Shift+F3',
    'Shift+F4',
    'Shift+F5',
    'Shift+F6',
    'Shift+F7',
    'Shift+F8',
    'Shift+F9',
    'Shift+F10',
    'Shift+F11',
    'Shift+F12',

    'Super+A',
    'Super+B',
    'Super+C',
    'Super+D',
    'Super+E',
    'Super+F',
    'Super+G',
    'Super+H',
    'Super+I',
    'Super+J',
    'Super+K',
    'Super+L',
    'Super+M',
    'Super+N',
    'Super+O',
    'Super+P',
    'Super+Q',
    'Super+R',
    'Super+S',
    'Super+T',
    'Super+U',
    'Super+V',
    'Super+W',
    'Super+X',
    'Super+Y',
    'Super+Z',

    'Super+0',
    'Super+1',
    'Super+2',
    'Super+3',
    'Super+4',
    'Super+5',
    'Super+6',
    'Super+7',
    'Super+8',
    'Super+9',

    'Super+~',
    'Super+!',
    'Super+@',
    'Super+#',
    'Super+$',

    'Super+Plus',
    'Super+Space',
    'Super+Tab',
    'Super+Capslock',
    'Super+Numlock',
    'Super+Scrollock',
    'Super+Backspace',
    'Super+Delete',
    'Super+Insert',
    'Super+Return',

    'Super+Up',
    'Super+Down',
    'Super+Left',
    'Super+Right',

    'Super+Esc',
    'Super+PageUp',
    'Super+PageDown',

    'Super+F1',
    'Super+F2',
    'Super+F3',
    'Super+F4',
    'Super+F5',
    'Super+F6',
    'Super+F7',
    'Super+F8',
    'Super+F9',
    'Super+F10',
    'Super+F11',
    'Super+F12',

    'CmdOrCtrl+AltOrCtrl+Shift+A',
    'CmdOrCtrl+AltOrCtrl+Shift+B',
    'CmdOrCtrl+AltOrCtrl+Shift+C',
    'CmdOrCtrl+AltOrCtrl+Shift+D',
    'CmdOrCtrl+AltOrCtrl+Shift+E',
    'CmdOrCtrl+AltOrCtrl+Shift+F',
    'CmdOrCtrl+AltOrCtrl+Shift+G',
    'CmdOrCtrl+AltOrCtrl+Shift+H',
    'CmdOrCtrl+AltOrCtrl+Shift+I',
    'CmdOrCtrl+AltOrCtrl+Shift+J',
    'CmdOrCtrl+AltOrCtrl+Shift+K',
    'CmdOrCtrl+AltOrCtrl+Shift+L',
    'CmdOrCtrl+AltOrCtrl+Shift+M',
    'CmdOrCtrl+AltOrCtrl+Shift+N',
    'CmdOrCtrl+AltOrCtrl+Shift+O',
    'CmdOrCtrl+AltOrCtrl+Shift+P',
    'CmdOrCtrl+AltOrCtrl+Shift+Q',
    'CmdOrCtrl+AltOrCtrl+Shift+R',
    'CmdOrCtrl+AltOrCtrl+Shift+S',
    'CmdOrCtrl+AltOrCtrl+Shift+T',
    'CmdOrCtrl+AltOrCtrl+Shift+U',
    'CmdOrCtrl+AltOrCtrl+Shift+V',
    'CmdOrCtrl+AltOrCtrl+Shift+W',
    'CmdOrCtrl+AltOrCtrl+Shift+X',
    'CmdOrCtrl+AltOrCtrl+Shift+Y',
    'CmdOrCtrl+AltOrCtrl+Shift+Z',

    'CmdOrCtrl+AltOrCtrl+Shift+0',
    'CmdOrCtrl+AltOrCtrl+Shift+1',
    'CmdOrCtrl+AltOrCtrl+Shift+2',
    'CmdOrCtrl+AltOrCtrl+Shift+3',
    'CmdOrCtrl+AltOrCtrl+Shift+4',
    'CmdOrCtrl+AltOrCtrl+Shift+5',
    'CmdOrCtrl+AltOrCtrl+Shift+6',
    'CmdOrCtrl+AltOrCtrl+Shift+7',
    'CmdOrCtrl+AltOrCtrl+Shift+8',
    'CmdOrCtrl+AltOrCtrl+Shift+9',

    'CmdOrCtrl+AltOrCtrl+Shift+~',
    'CmdOrCtrl+AltOrCtrl+Shift+!',
    'CmdOrCtrl+AltOrCtrl+Shift+@',
    'CmdOrCtrl+AltOrCtrl+Shift+#',
    'CmdOrCtrl+AltOrCtrl+Shift+$',

    'CmdOrCtrl+AltOrCtrl+Shift+Plus',
    'CmdOrCtrl+AltOrCtrl+Shift+Space',
    'CmdOrCtrl+AltOrCtrl+Shift+Tab',
    'CmdOrCtrl+AltOrCtrl+Shift+Capslock',
    'CmdOrCtrl+AltOrCtrl+Shift+Numlock',
    'CmdOrCtrl+AltOrCtrl+Shift+Scrollock',
    'CmdOrCtrl+AltOrCtrl+Shift+Backspace',
    'CmdOrCtrl+AltOrCtrl+Shift+Delete',
    'CmdOrCtrl+AltOrCtrl+Shift+Insert',
    'CmdOrCtrl+AltOrCtrl+Shift+Return',

    'CmdOrCtrl+AltOrCtrl+Shift+Up',
    'CmdOrCtrl+AltOrCtrl+Shift+Down',
    'CmdOrCtrl+AltOrCtrl+Shift+Left',
    'CmdOrCtrl+AltOrCtrl+Shift+Right',

    'CmdOrCtrl+AltOrCtrl+Shift+Esc',
    'CmdOrCtrl+AltOrCtrl+Shift+PageUp',
    'CmdOrCtrl+AltOrCtrl+Shift+PageDown',

    'CmdOrCtrl+AltOrCtrl+Shift+F1',
    'CmdOrCtrl+AltOrCtrl+Shift+F2',
    'CmdOrCtrl+AltOrCtrl+Shift+F3',
    'CmdOrCtrl+AltOrCtrl+Shift+F4',
    'CmdOrCtrl+AltOrCtrl+Shift+F5',
    'CmdOrCtrl+AltOrCtrl+Shift+F6',
    'CmdOrCtrl+AltOrCtrl+Shift+F7',
    'CmdOrCtrl+AltOrCtrl+Shift+F8',
    'CmdOrCtrl+AltOrCtrl+Shift+F9',
    'CmdOrCtrl+AltOrCtrl+Shift+F10',
    'CmdOrCtrl+AltOrCtrl+Shift+F11',
    'CmdOrCtrl+AltOrCtrl+Shift+F12',

    'CmdOrCtrl+Alt+A',
    'CmdOrCtrl+Alt+B',
    'CmdOrCtrl+Alt+C',
    'CmdOrCtrl+Alt+D',
    'CmdOrCtrl+Alt+E',
    'CmdOrCtrl+Alt+F',
    'CmdOrCtrl+Alt+G',
    'CmdOrCtrl+Alt+H',
    'CmdOrCtrl+Alt+I',
    'CmdOrCtrl+Alt+J',
    'CmdOrCtrl+Alt+K',
    'CmdOrCtrl+Alt+L',
    'CmdOrCtrl+Alt+M',
    'CmdOrCtrl+Alt+N',
    'CmdOrCtrl+Alt+O',
    'CmdOrCtrl+Alt+P',
    'CmdOrCtrl+Alt+Q',
    'CmdOrCtrl+Alt+R',
    'CmdOrCtrl+Alt+S',
    'CmdOrCtrl+Alt+T',
    'CmdOrCtrl+Alt+U',
    'CmdOrCtrl+Alt+V',
    'CmdOrCtrl+Alt+W',
    'CmdOrCtrl+Alt+X',
    'CmdOrCtrl+Alt+Y',
    'CmdOrCtrl+Alt+Z',

    'CmdOrCtrl+Alt+0',
    'CmdOrCtrl+Alt+1',
    'CmdOrCtrl+Alt+2',
    'CmdOrCtrl+Alt+3',
    'CmdOrCtrl+Alt+4',
    'CmdOrCtrl+Alt+5',
    'CmdOrCtrl+Alt+6',
    'CmdOrCtrl+Alt+7',
    'CmdOrCtrl+Alt+8',
    'CmdOrCtrl+Alt+9',

    'CmdOrCtrl+Alt+~',
    'CmdOrCtrl+Alt+!',
    'CmdOrCtrl+Alt+@',
    'CmdOrCtrl+Alt+#',
    'CmdOrCtrl+Alt+$',

    'CmdOrCtrl+Alt+Plus',
    'CmdOrCtrl+Alt+Space',
    'CmdOrCtrl+Alt+Tab',
    'CmdOrCtrl+Alt+Capslock',
    'CmdOrCtrl+Alt+Numlock',
    'CmdOrCtrl+Alt+Scrollock',
    'CmdOrCtrl+Alt+Backspace',
    'CmdOrCtrl+Alt+Delete',
    'CmdOrCtrl+Alt+Insert',
    'CmdOrCtrl+Alt+Return',

    'CmdOrCtrl+Alt+Up',
    'CmdOrCtrl+Alt+Down',
    'CmdOrCtrl+Alt+Left',
    'CmdOrCtrl+Alt+Right',

    'CmdOrCtrl+Alt+Esc',
    'CmdOrCtrl+Alt+PageUp',
    'CmdOrCtrl+Alt+PageDown',

    'CmdOrCtrl+Alt+F1',
    'CmdOrCtrl+Alt+F2',
    'CmdOrCtrl+Alt+F3',
    'CmdOrCtrl+Alt+F4',
    'CmdOrCtrl+Alt+F5',
    'CmdOrCtrl+Alt+F6',
    'CmdOrCtrl+Alt+F7',
    'CmdOrCtrl+Alt+F8',
    'CmdOrCtrl+Alt+F9',
    'CmdOrCtrl+Alt+F10',
    'CmdOrCtrl+Alt+F11',
    'CmdOrCtrl+Alt+F12',

    'Alt+Shift+A',
    'Alt+Shift+B',
    'Alt+Shift+C',
    'Alt+Shift+D',
    'Alt+Shift+E',
    'Alt+Shift+F',
    'Alt+Shift+G',
    'Alt+Shift+H',
    'Alt+Shift+I',
    'Alt+Shift+J',
    'Alt+Shift+K',
    'Alt+Shift+L',
    'Alt+Shift+M',
    'Alt+Shift+N',
    'Alt+Shift+O',
    'Alt+Shift+P',
    'Alt+Shift+Q',
    'Alt+Shift+R',
    'Alt+Shift+S',
    'Alt+Shift+T',
    'Alt+Shift+U',
    'Alt+Shift+V',
    'Alt+Shift+W',
    'Alt+Shift+X',
    'Alt+Shift+Y',
    'Alt+Shift+Z',

    'Alt+Shift+0',
    'Alt+Shift+1',
    'Alt+Shift+2',
    'Alt+Shift+3',
    'Alt+Shift+4',
    'Alt+Shift+5',
    'Alt+Shift+6',
    'Alt+Shift+7',
    'Alt+Shift+8',
    'Alt+Shift+9',

    'Alt+Shift+~',
    'Alt+Shift+!',
    'Alt+Shift+@',
    'Alt+Shift+#',
    'Alt+Shift+$',

    'Alt+Shift+Plus',
    'Alt+Shift+Space',
    'Alt+Shift+Tab',
    'Alt+Shift+Capslock',
    'Alt+Shift+Numlock',
    'Alt+Shift+Scrollock',
    'Alt+Shift+Backspace',
    'Alt+Shift+Delete',
    'Alt+Shift+Insert',
    'Alt+Shift+Return',

    'Alt+Shift+Up',
    'Alt+Shift+Down',
    'Alt+Shift+Left',
    'Alt+Shift+Right',

    'Alt+Shift+Esc',
    'Alt+Shift+PageUp',
    'Alt+Shift+PageDown',

    'Alt+Shift+F1',
    'Alt+Shift+F2',
    'Alt+Shift+F3',
    'Alt+Shift+F4',
    'Alt+Shift+F5',
    'Alt+Shift+F6',
    'Alt+Shift+F7',
    'Alt+Shift+F8',
    'Alt+Shift+F9',
    'Alt+Shift+F10',
    'Alt+Shift+F11',
    'Alt+Shift+F12',






    


]